updated

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,41 +1,45 @@
 version: 2.1
-
+docker_anchor: &docker_node
+  docker:
+    - image: cimg/node:13.8.0
 commands:
   destroy-environment:
     description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
-    parameters:
-      # Add parameter here   
     steps:
       - run:
           name: Destroy environments
           when: on_fail
           command: |
-            # Your code here
-            exit 1
+              aws cloudformation delete-stack --stack-name "fwdp3-backend-${CIRCLE_WORKFLOW_ID:0:8}"
+              aws cloudformation delete-stack --stack-name "fwdp3-frontend-${CIRCLE_WORKFLOW_ID:0:8}"
+              aws s3 rb --force "s3://fwdp3-${CIRCLE_WORKFLOW_ID:0:8}"
+              
 
   revert-migrations:
-    description: Revert the last migration if successfully run in the current workflow.
-    parameters:
-      # Add parameter here     
+    description: Revert the last migration if successfully run in the current workflow.   
     steps:
       - run:
           name: Revert migrations
-          # Add when this will run
           command: |
             # Curl command here to see if there was a successful migration associated with the workflow id, store result in SUCCESS variable
-            SUCCESS = 1
+            SUCCESS=$(curl --insecure https://kvdb.io/77wBymZXydkb2AyAhb56ny/migration_$\{CIRCLE_WORKFLOW_ID:0:7\})
+           
+           # not accessible
+           ## SUCCESS=$(curl -H "token: 9165e6d8-3cdf-45d3-9039-be52e27bfd76" --request GET https://api.memstash.io/values/${CIRCLE_WORKFLOW_ID:0:8})
+            
             if(( $SUCCESS==1 )); 
-            then
-            #  cd ~/project/backend
-            #  npm install
-            #  Add revert code here. You can find this in the Getting Started section.
-              exit 1
+            then 
+              npm cache clean 
+              rm -rf node_modules
+              cd ~/project/backend
+              npm i
+              npm run migrations:revert
+            
             fi
             
 jobs:
   build-frontend:
-    docker:
-      - image: circleci/node:13.8.0
+     <<: *docker_nodee
     steps:
       - checkout
       - restore_cache:
@@ -43,15 +47,15 @@ jobs:
       - run:
           name: Build front-end
           command: |
-            # Your code here
-            exit 1
+            cd frontend
+            npm install
+            npm run build
       - save_cache:
           paths: [frontend/node_modules]
           key: frontend-build
 
   build-backend:
-    docker:
-      - image: circleci/node:13.8.0
+     <<: *docker_nodee
     steps:
       - checkout
       - restore_cache:
@@ -59,207 +63,305 @@ jobs:
       - run:
           name: Back-end build
           command: |
-             # Your code here
-             exit 1
+            cd backend
+            npm install
+            npm run build
       - save_cache:
           paths: [backend/node_modules]
           key: backend-build
 
   test-frontend:
     docker:
-      # Docker image here
+      <<: *docker_node
     steps:
-      # Checkout code from git
-      # Restore from cache
-      # Your job code here
+      - checkout
+      - restore_cache:
+        keys: [frontend-build]
+      - run :
+          name : Front-end-test
+          command: |
+            cd frontend
+            npm install
+            npm run test 
                 
   test-backend:
     docker:
-      # Docker image here
+      <<: *docker_node
     steps:
-      # Checkout code from git
-      # Restore from cache
-      # Your job code here
+      - checkout
+      - restore_cache:
+        keys: [backend-build]
+      - run :
+          name : backend-end-test
+          command: |
+            cd backend
+            npm install
+            npm run test 
             
   scan-frontend:
     docker:
-      # Docker image here
+      <<: *docker_node
     steps:
-      # Checkout code from git
-      # Restore from cache
-      # Your job code here
+      - checkout
+      - restore_cache:
+        keys: [frontend-build]
+      - run :
+          name : Front-end-scan
+          command: |
+            cd frontend
+            npm install
+            npm audit
 
   scan-backend:
     docker:
-      # Docker image here
+      <<: *docker_node
     steps:
-      # Checkout code from git
-      # Restore from cache
-      # Your job code here
+      - checkout
+      - restore_cache:
+        keys: [backend-build]
+      - run :
+          name : backend-end-scan
+          command: |
+            cd frontend
+            npm install
+            npm audit
 
   deploy-infrastructure:
     docker:
-      # Docker image here that supports AWS CLI
+      - image: amazon/aws-cli
     steps:
-      # Checkout code from git
+      - checkout
       - run:
           name: Ensure back-end infrastructure exists
           command: |
             aws cloudformation deploy \
               --template-file .circleci/files/backend.yml \
-              #--tags project=your-tag \
-              # --stack-name "your back-end stack name with workflow id" \
-              # --parameter-overrides ID="your workflow id"  
-              exit 1
+              --tags project=fwdp3 \
+              --stack-name "fwdp3-backend-${CIRCLE_WORKFLOW_ID:0:8}" \
+              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:8}"  
       - run:
           name: Ensure front-end infrastructure exist
           command: |
             aws cloudformation deploy \
               --template-file .circleci/files/frontend.yml \
-              #--tags project=your-tag \
-              # --stack-name "your front-end stack name with workflow id" \
-              # --parameter-overrides ID="your workflow id"  
-              exit 1
+              --tags project=fwdp3 \
+              --stack-name "fwdp3-frontend-${CIRCLE_WORKFLOW_ID:0:8}" \
+              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:8}" 
       - run:
           name: Add back-end ip to ansible inventory
           command: |
-            # Your code here
-            exit 1
+            echo "[hosts]" > .circleci/ansible/inventory.txt
+            aws ec2 describe-instances \
+              --query "Reservations[*].Instances[*].PublicIpAddress" \
+              --output=text >> .circleci/ansible/inventory.txt
       - persist_to_workspace:
           root: ~/
           paths:
             - project/.circleci/ansible/inventory.txt
-      # Here's where you will add some code to rollback on failure      
+      -destroy-environment    
 
   configure-infrastructure:
     docker:
       # Docker image here that supports Ansible
+      image: python:3.7-alpine3.11
     steps:
-      # Checkout code from git
+      - checkout
+
       # Add ssh keys with fingerprint
-      # attach workspace
+      - add ssh-keys:
+          fingerprints: ["19:d7:6f:6d:07:a0:f8:4f:55:89:25:57:1b:75:f8:39"]
+      - attach_workspace:
+          at: ~/
       - run:
           name: Install dependencies
           command: |
-            # Your code here
-            exit 1
+                apk add --update ansible
       - run:
           name: Configure server
           command: |
-            # Your code here
-            exit 1
-      # Here's where you will add some code to rollback on failure      
+            ansible-playbook -i ~/project/.circleci/ansible/inventory.txt .circleci/ansible/configure-server.yml
+      # Here's where you will add some code to rollback on failure 
+      - destroy-environment
 
   run-migrations:
-    docker:
-      # Docker image here that supports NodeJS
+      <<: *docker_node
     steps:
-      # Checkout code from git
+      - checkout
       - run:
           name: Run migrations
           command: |
-            # Your code here
-            exit 1
+            cd backend
+            npm run migrations > migrations.txt
       - run:
-          name: Send migration results to memstash
+          name: Send migration results to KVBD 
           command: |
-            # Your code here
-            exit 1
-     # Here's where you will add some code to rollback on failure      
+            if grep -q "has been executed successfully." ~/project/backend/migrations.txt
+            then
+              echo "Migration Succesful"
+              curl https://kvdb.io/77wBymZXydkb2AyAhb56ny/migration_${CIRCLE_WORKFLOW_ID:0:8}  -k -d '1'
+            else
+              echo "Migration failed"
+              curl https://kvdb.io/77wBymZXydkb2AyAhb56ny/migration_${CIRCLE_WORKFLOW_ID:0:8}  -k -d '0'
+            fi
+      - revert-migrations
+      - destroy-environment
+     
 
   deploy-frontend:
     docker:
-      # Docker image here that supports AWS CLI
+      - image: amazon/aws-cli
     steps:
-      # Checkout code from git
+      - checkout
+      - restore_cache:
+        keys: [frontend-build]
+      - attach_workspace:
+          at: ~/
+      
       - run:
           name: Install dependencies
           command: |
-            # your code here
+            sudo apt update
+            sudo apt install nodejs
+            
       - run:
           name: Get backend url
           command: |
-            # your code here
+            export BACKEND_IP=$(aws ec2 describe-instances --query "Reservations[*].Instances[*].PublicIpAddress" --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:8}" --output=text)
             export API_URL="http://${BACKEND_IP}:3030"
-            echo "${API_URL}"
+            echo API_URL="http://${BACKEND_IP}:3030" >> frontend/.env
       - run:
           name: Deploy frontend objects
           command: |
-            # your code here
-      # Here's where you will add some code to rollback on failure      
+            cd frontend
+            npm install
+            npm run build
+            tar -czvf artifact-"${CIRCLE_WORKFLOW_ID:0:8}".tar.gz dist
+            aws s3 cp dist s3://fwdp3-${CIRCLE_WORKFLOW_ID:0:8} --recursive
+      - revert-migrations
+      - destroy-environment     
                     
   deploy-backend:
     docker:
-      # Docker image here that supports Ansible
+      image: python:3.7-alpine3.11
     steps:
-      # Checkout code from git
-      # Add ssh keys with fingerprint
-      # attach workspace
+      - checkout
+      - restore_cache:
+        keys: [backend-build]
+      - attach_workspace:
+          at: ~/
       - run:
           name: Install dependencies
           command: |
-            # your code here
+            sudo apt update
+            sudo apt install nodejs
+            sudo apt install -y awscli
       - run:
           name: Deploy backend
           command: |
-            # your code here
+            tar -C backend -czvf artifact.tar.gz .
+            cd .circleci/ansible
+            ansible-playbook -i inventory.txt deploy-backend.yml
+      - revert-migrations
+      - destroy-environment     
       # Here's where you will add some code to rollback on failure  
 
   smoke-test:
-    docker:
-      # Lightweight Docker image 
+     <<: *docker_node 
     steps:
-      # Checkout code from git
+      - checkout
       - run:
           name: Install dependencies
           command: |
-            # your code here
+            sudo apt update
+            sudo apt install -y python3 python3-pip
+            sudo apt install -y awscli
       - run:
           name: Get backend url
           command: |
-            # your code here
+            export BACKEND_IP=$(aws ec2 describe-instances --query "Reservations[*].Instances[*].PublicIpAddress" --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:8}" --output=text)
+            export API_URL="http://${BACKEND_IP}:3030"
+            
       - run:
           name: Backend smoke test.
           command: |
-            # your code here
+            if curl "${API_URL}/api/status" | grep "ok"
+            then
+                exit 0
+            else
+                exit 1
+            fi
       - run:
           name: Frontend smoke test.
           command: |
-            # your code here
-      # Here's where you will add some code to rollback on failure  
+            export FRONTEND_URL="http://udapeople-${CIRCLE_WORKFLOW_ID}.s3-website-us-east-1.amazonaws.com/index.html"
+            echo "-------------------- Frontend url ------------------------"
+            echo $FRONTEND_URL
+            if curl $FRONTEND_URL | grep "Welcome"
+            then
+              exit 0
+            else
+              exit 1
+            fi
+      - revert-migrations
+      - destroy-environment     
 
   cloudfront-update:
     docker:
-      # Docker image here that supports AWS CLI
+      - image: amazon/aws-cli
     steps:
-      # Checkout code from git
+      -
       - run:
           name: Install dependencies
           command: |
-            # your code here
+            sudo apt update
+            sudo apt install -y python3 python3-pip
+            sudo apt install nodejs
       - run:
           name: Update cloudfront distribution
           command: |
-            # your code here
-      # Here's where you will add some code to rollback on failure  
+            export OldWorkflowID=$(aws cloudformation \
+            list-exports --query "Exports[?Name==\`WorkflowID\`].Value" \
+            --no-paginate --output text)
+            echo $OldWorkflowID > oldWorkflowId.txt
+            aws cloudformation update-stack \
+            --use-previous-template \
+            --stack-name fwdstack \
+            --parameters ParameterKey=WorkflowID,ParameterValue=${CIRCLE_WORKFLOW_ID:0:8}
+        - run:
+          name: install tar utilities
+          command: |
+            npm install -y tar gzip
+      - persist_to_workspace:
+          root: ~/
+          paths:
+            - project/oldWorkflowId.txt
+      - revert-migrations
+      - destroy-environment
 
 cleanup:
     docker:
-      # Docker image here
+      - image: amazon/aws-cli
     steps:
-      # Checkout code from git
+      - checkout
       - run:
           name: Get old stack workflow id
           command: |
-            # your code here
-            export OldWorkflowID="the id here"
-            export STACKS=[] #put the list of stacks here
+            npm install -y tar gzip
+      - attach_workspace:
+          at: ~/
       - run:
           name: Remove old stacks and files
           command: |
+            export OldWorkflowID=$(cat ~/project/oldWorkflowId.txt)
+            export STACKS=($(aws cloudformation list-stacks --query "StackSummaries[*].StackName" \
+            --stack-status-filter CREATE_COMPLETE --no-paginate --output text)) 
             if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
             then
-              # your code here
+              aws s3 rm "s3://udapeople-${OldWorkflowID}" --recursive
+              aws s3 rb s3://udapeople-${OldWorkflowID} --force
+              aws cloudformation delete-stack --stack-name "backend-${OldWorkflowID}"
+              aws cloudformation delete-stack --stack-name "frontend-${OldWorkflowID}"
+              echo "Stacks deleted succesfully"
             fi
             
 
@@ -280,7 +382,7 @@ workflows:
           requires: [test-frontend, test-backend, scan-frontend, scan-backend]
           filters:
             branches:
-              only: [test-feature-branch]
+              only: [master]
       - configure-infrastructure:
           requires: [deploy-infrastructure]
       - run-migrations:
